### PR TITLE
Make CachingWriter a drop-in replacement for Plugin

### PR DESCRIPTION
**Pull request by joliss**
As requested by @stefanpenner. First three commits are actually good to merge I think.

Fourth one still requires updating to README, and it probably also makes sense to get the API to mimic Plugin, so that it's a drop-in-replacement for broccoli-plugin. I'll do that soon.

### CODE REVIEW

**Comment by stefanpenner** [comment]
@joliss if you have a chance to share a list of tasks needed to complete this?

- [ ] maybe
- [ ] a 
- [ ] checklist

so others can jump in if needed.

**Comment by joliss** [comment]
I think this is basically good to merge - `CachingWriter` is now a drop-in replacement for `Plugin`. Since we're redoing the API anyway, I was wondering if we should also make the following changes:

* Rename the `filterFromCache.include` option to something like `cacheInclude` (is there a better name?), and same for `exclude`, so that we don't need a nested object?

* To make the API more compact, it seems like we could sensibly fold the `inputFiles` functionality into `filterFromCache.include` - e.g. the `filterFromCache.include` array could allow for relative paths (or globs?) in addition to regexes.

    `inputFiles` option is currently undocumented and not integration-tested (the logic is unit-tested, but we never do `new CachingWriter(..., { inputFiles: ... })` in the tests). So I'm wondering if, in the interest of getting this PR merged and released soon, it might be easiest drop the `inputFiles` option for now? We can then re-add the functionality in a subsequent release by making `filterFromCache.include` more powerful.

**Comment by joliss** [comment]
Let me know if this is OK with you, and I'll make the changes and update this PR.

**Comment by rwjblue** [comment]
> Rename the filterFromCache.include option to something like cacheInclude

:+1:

> So I'm wondering if, in the interest of getting this PR merged and released soon, it might be easiest drop the inputFiles option for now?

I'm not really sure. `inputFiles` is actually a bit of coupling to things like `broccoli-sourcemap-concat` (whose API is to use `inputFiles`). The idea here is that when `inputFiles` is specified to a limited subset, we do much smarter things about comparing hashes (it is a huge speedup).

I'll defer to @stefanpenner on this one (as this is recently landed functionality).

**Comment by joliss** [comment]
> inputFiles is actually a bit of coupling to things like broccoli-sourcemap-concat 

My idea would be to pass it on in the super call ([example](https://github.com/joliss/broccoli-es6modules/blob/a33016fa44064b17606fd469b867250c3c4f9f4d/index.js#L36-L38)), i.e.

```js
  CachingWriter.call(this, [inputNode], {
    annotation: options.annotation
    cacheInclude: options.inputFiles
  });
```

**Comment by stefanpenner** [comment]
In practice we could drop inputFiles and make it just part of includes

**Comment by joliss** [comment]
Okay, done - rimraf is async and option is called `cacheInclude`. Handing over to @stefanpenner for finishing up the `inputFiles` part. :)

**Comment by timmfin** [comment]
+1 to `cacheInclude` and `cacheExclude` (over `filterFromCache.*`... my bad for the [original name](https://github.com/ember-cli/broccoli-caching-writer/pull/11) :stuck_out_tongue_winking_eye: )

And +1 to merging `inputFiles` into `cacheInclude`. While slick and seemingly convenient, I think it is a bad idea to encourage too much options key sharing, especially for less used options (explicit > implicit)

**Comment by joliss** [comment]
I'd like to finish up this PR by allowing globs for `cacheInclude`. The code complexity goes up a lot from (a) allowing both regexes and globs, and (b) having a cacheExclude option. I don't believe regexes and cacheExclude are actually needed by any caching-writer subclasses.

A GitHub search suggests that some plugins pass on an `exclude` option from their constructor options to CachingWriter, but they probably only do this "because they can" - it's not clear to me that this is really needed. Here are the instances I found: https://github.com/MojoJojo/broccoli-svg-sprite/blob/01ae3933e7ea08a60ce46532bb7d01cd288b37ba/index.js#L41-L43 https://github.com/chancancode/hn-reader/blob/0c5c2dcd0a913b681b41d3fea3103e23be646871/lib/fixtures-packer/lib/broccoli-mapper.js#L24-L26 https://github.com/markuskobler/broccoli-jsx/blob/112713402d578d0dda4044b706e0a492750a8bb3/lib/index.js#L25 https://github.com/markuskobler/broccoli-jsx2idom/blob/30e9d9be588b470477863e5f10cb66288762a3f3/lib/index.js#L25 https://github.com/markuskobler/broccoli-closure-plugin/blob/cd6ac46e52898aa283555ff71f5b0156d6a5099b/lib/index.js#L23 https://github.com/timmfin/broccoli-dependencies/blob/33effe5b20b28cecac2993f30c12be731d3d280d/copy-dependencies.coffee#L41

As we're redoing the API, can we, in the interest of keeping complexity manageable, (a) drop regex support in favor of globs, and (b) drop the `exclude` (`cacheExclude`) option? If we do this, it means that we only need to pass on `cacheInclude` to walkSync, and there's no additional code needed on CachingWriter's end.

**Comment by rwjblue** [comment]
I am perfectly fine removing regexp and exclude support (we will have to bump major versions anyways), then seeing if they are needed as the various subclasses update.

**Comment by joliss** [comment]
Okay, so it turns out that redoing the cache include/exclude logic is actually a bit trickier than I thought, at least if I want to preserve invalidation logging. I'd like to redo it properly at some point, but that will require more work, so for now I've just kept `inputFiles` so we can move forward with the Broccoli API upgrade.

I believe this is PR is good to merge!

**Comment by joliss** [comment]
When you've merged this, can you release 2.0.0 please? Then I can send some more PRs that will depend on the new release.

**Comment by stefanpenner** [comment]
thanks @joliss 2.0.0 released.

As we have been working through some of the core plugins, im sure we are accumulating some cleanup plans. We should likely circle around sometime soon, and consider cleanup releases. (to remove some of the cruft, we have built up)

**Pull request merged**
